// This file was auto generated by resource-sync tools.

import en_waimai_home from './en/waimai_home.json';
import zhCN_waimai_home from './zh-CN/waimai_home.json';
import zhHK_waimai_home from './zh-HK/waimai_home.json';

const resources = {
  en: {
    waimai_home: en_waimai_home,
  },
  'zh-CN': {
    waimai_home: zhCN_waimai_home,
  },
  'zh-HK': {
    waimai_home: zhHK_waimai_home,
  },
};

export default resources;
