// This file was auto generated by resource-sync tools.

import en_translation from './en/translation.json';
import zhCN_translation from './zh-CN/translation.json';
import zhHK_translation from './zh-HK/translation.json';
import zuZA_translation from './zu-ZA/translation.json';

const resources = {
    'en': {
        translation: en_translation
    },
    'zh-CN': {
        translation: zhCN_translation
    },
    'zh-HK': {
        translation: zhHK_translation
    },
    'zu-ZA': {
        translation: zuZA_translation
    }
};

export default resources;