// This file was auto generated by resource-sync tools.

import zh_waimai_home from './zh/waimai_home.json';
import zh_waimai_home_f from './zh/waimai_home_f.json';


const resources = {
    'zh': {
        waimai_home: zh_waimai_home,
        waimai_home_f: zh_waimai_home_f
    }
};

export default resources;